<?php

namespace App\Models;

use App\Enums\BillingStatementStatus;
use App\Models\Concerns\BelongsToCompany;
use Database\Factories\BillingStatementFactory;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * One month's bill for a company — generated by App\Actions\GenerateBillingStatement.
 * Its items are snapshots of what was charged; nothing here is recomputed
 * from the current fee configuration.
 */
class BillingStatement extends Model
{
    /** @use HasFactory<BillingStatementFactory> */
    use BelongsToCompany, HasFactory;

    protected $fillable = [
        'company_id',
        'reference',
        'billing_number',
        'period_start',
        'period_end',
        'issued_on',
        'due_on',
        'total',
        'status',
        'paid_at',
        'amount_received',
        'carry_over_amount',
        'carried_to_statement_id',
        'generated_by',
    ];

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'period_start' => 'date',
            'period_end' => 'date',
            'issued_on' => 'date',
            'due_on' => 'date',
            'billing_number' => 'integer',
            'total' => 'decimal:2',
            'status' => BillingStatementStatus::class,
            'paid_at' => 'datetime',
            'amount_received' => 'decimal:2',
            'carry_over_amount' => 'decimal:2',
        ];
    }

    /**
     * @return HasMany<BillingStatementItem, $this>
     */
    public function items(): HasMany
    {
        return $this->hasMany(BillingStatementItem::class);
    }

    /**
     * The later statement this one's excess / shortage was carried to.
     *
     * @return BelongsTo<BillingStatement, $this>
     */
    public function carriedTo(): BelongsTo
    {
        return $this->belongsTo(BillingStatement::class, 'carried_to_statement_id');
    }

    /**
     * Paid statements whose excess or shortage hasn't been put on a later
     * bill yet — the next statement generated for the company takes them.
     *
     * @param  Builder<BillingStatement>  $query
     */
    public function scopeAwaitingCarryOver(Builder $query): void
    {
        $query->where('status', BillingStatementStatus::Paid->value)
            ->where('carry_over_amount', '!=', 0)
            ->whereNull('carried_to_statement_id');
    }

    /**
     * @return BelongsTo<User, $this>
     */
    public function generator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'generated_by');
    }
}
